"""initial schema - full AEGISAI domain model

Revision ID: 5813ae5de54c
Revises: 
Create Date: 2026-08-11 18:01:08.223982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # NOTE: alembic autogenerate does not add this import
# automatically for pgvector columns — it's needed by hand every time you
# regenerate a migration that touches ResearchSource.embedding.


# revision identifiers, used by Alembic.
revision: str = '5813ae5de54c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_opportunities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('automation_potential', sa.Enum('low', 'medium', 'high', name='automation_potential'), nullable=False),
    sa.Column('human_ai_responsibility', sa.Enum('ai_automates', 'ai_augments', 'human_led', 'human_approval_required', name='human_ai_responsibility'), nullable=False),
    sa.Column('business_benefit', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_jobs',
    sa.Column('target_type', sa.Enum('process', 'role', 'skill', 'ai_opportunity', name='analysis_target_type'), nullable=False),
    sa.Column('input_name', sa.String(length=300), nullable=False),
    sa.Column('input_context', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysis_job_status'), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stage_log', sa.JSON(), nullable=False),
    sa.Column('result_entity_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('source_type', sa.Enum('process', 'activity', 'role', 'skill', 'ai_opportunity', name='graph_node_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('process', 'activity', 'role', 'skill', 'ai_opportunity', name='graph_node_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('edge_label', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_edges_source', 'graph_edges', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_graph_edges_target', 'graph_edges', ['target_type', 'target_id'], unique=False)
    op.create_table('industries',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('research_sources',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('law_regulation', 'regulatory_guidance', 'industry_standard', 'research', 'vendor_information', 'general_web_content', name='source_type'), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('retrieved_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('current_responsibilities', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('trend_classification', sa.Enum('emerging', 'increasing', 'ai_augmented', 'changing', 'declining', 'enduring_human_capability', 'unclassified', name='skill_trend'), nullable=False),
    sa.Column('trend_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_assessments',
    sa.Column('ai_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('factor_repetitiveness', sa.Float(), nullable=False),
    sa.Column('factor_data_availability', sa.Float(), nullable=False),
    sa.Column('factor_predictability', sa.Float(), nullable=False),
    sa.Column('factor_digitalization', sa.Float(), nullable=False),
    sa.Column('factor_ai_capability_fit', sa.Float(), nullable=False),
    sa.Column('factor_rationale', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('impact_band', sa.Enum('low', 'medium', 'high', 'very_high', name='impact_band'), nullable=False),
    sa.Column('scoring_model_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_opportunity_id')
    )
    op.create_table('ai_opportunity_role_impacts',
    sa.Column('ai_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_opportunity_id', 'role_id')
    )
    op.create_table('ai_opportunity_skill_impacts',
    sa.Column('ai_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_opportunity_id', 'skill_id')
    )
    op.create_table('evidence',
    sa.Column('research_source_id', sa.UUID(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('process', 'activity', 'role', 'skill', 'ai_opportunity', 'ai_assessment', name='related_entity_type'), nullable=False),
    sa.Column('related_entity_id', sa.UUID(), nullable=False),
    sa.Column('extracted_finding', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('future_responsibilities',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('driven_by_ai_opportunity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['driven_by_ai_opportunity_id'], ['ai_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_skills',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id')
    )
    op.create_table('value_chains',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_purpose', sa.Text(), nullable=True),
    sa.Column('current_challenges', sa.Text(), nullable=True),
    sa.Column('value_chain_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_ai_impact_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['value_chain_id'], ['value_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_ai_opportunities',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('ai_opportunity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ai_opportunity_id'], ['ai_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'ai_opportunity_id')
    )
    op.create_table('activity_roles',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_roles')
    op.drop_table('activity_ai_opportunities')
    op.drop_table('activities')
    op.drop_table('processes')
    op.drop_table('value_chains')
    op.drop_table('role_skills')
    op.drop_table('organizations')
    op.drop_table('future_responsibilities')
    op.drop_table('evidence')
    op.drop_table('ai_opportunity_skill_impacts')
    op.drop_table('ai_opportunity_role_impacts')
    op.drop_table('ai_assessments')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('research_sources')
    op.drop_table('industries')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('analysis_jobs')
    op.drop_table('ai_opportunities')
    # ### end Alembic commands ###

    # Alembic autogenerate does NOT drop the custom ENUM types it created in
    # upgrade() — verified locally: downgrade-then-upgrade failed with
    # "type already exists" until these were added by hand. Every pg_enum()
    # in app/models/base.py needs a matching line here.
    sa.Enum(name='automation_potential').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='human_ai_responsibility').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='impact_band').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analysis_target_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analysis_job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='related_entity_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='skill_trend').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='graph_node_type').drop(op.get_bind(), checkfirst=True)
