"""add embedding columns to roles skills activities

Revision ID: a1ea22aae0e2
Revises: 5813ae5de54c
Create Date: 2026-08-12 11:28:07.991808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # NOTE: alembic autogenerate does not add this import automatically


# revision identifiers, used by Alembic.
revision: str = 'a1ea22aae0e2'
down_revision: Union[str, Sequence[str], None] = '5813ae5de54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('roles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'embedding')
    op.drop_column('roles', 'embedding')
    op.drop_column('activities', 'embedding')
    # ### end Alembic commands ###
